import "./globals.css";

import { Cormorant_Garamond as CormorantGaramond } from "next/font/google";

export const cormorantGaramond = CormorantGaramond({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-cormorant",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased ${cormorantGaramond.variable}`}>
        {children}
      </body>
    </html>
  );
}
